project:
  type: default

execute:
  echo: false
  warning: false
  error: false

format:
  revealjs:
    theme: white
    css: theme.scss
    slide-number: c/t
    transition: fade
    center: false
    smaller: false
    incremental: false
    controls: true
    progress: true
    hash: true
    preview-links: auto
    footer: "Lithium Extraction with ePC-SAFT"
    chalkboard: false

